micronaut:
    application:
        name: com-iphayao-microservice-demo
                
#Uncomment to set server port
    server:
        port: 8080

datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver

jpa:
    default:
        packages-to-scan:
        - 'com.iphayao.microservice.demo'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
